name: Android Main CI

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/**"
      - ".idea/"
      - "doc/*"
      - "*.md"
      - "app/src/assets/**"
      - ".github/workflows/crowdin.yml"
      - "crowdin.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        shell: bash
        run: ./gradlew assembleCanary

      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: app-${{ github.event.release.tag_name }}.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          repo-token: ${{ github.token }}
          content-type: application/zip

